// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MuhktarWebApp.Data;
using MuhktarWebApp.Models.Classes;
using System;

namespace MuhktarWebApp.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MuhktarWebApp.Models.Classes.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MaxWeight");

                    b.Property<int>("MinWeight");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<double>("Price");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("MuhktarWebApp.Models.Classes.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("CashBack");

                    b.Property<int>("CategoryId");

                    b.Property<string>("Customer")
                        .IsRequired();

                    b.Property<int>("CustomerType");

                    b.Property<double>("Price");

                    b.Property<int>("RouteId");

                    b.Property<int>("State");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RouteId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("MuhktarWebApp.Models.Classes.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("End")
                        .IsRequired();

                    b.Property<DateTime>("EndDate");

                    b.Property<int>("Price");

                    b.Property<string>("Start")
                        .IsRequired();

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Id");

                    b.ToTable("Route");
                });

            modelBuilder.Entity("MuhktarWebApp.Models.Classes.Order", b =>
                {
                    b.HasOne("MuhktarWebApp.Models.Classes.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MuhktarWebApp.Models.Classes.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
